# 서버 설정
server:
  port: 8080  # 서버 포트 설정
# 스프링 프로파일 설정 (dev, prod 등 환경별로 설정 분리 가능)
spring:
  profiles:
    active: dev # 현재 사용할 프로파일 설정
  datasource:
    url: jdbc:mysql://localhost:3306/outsourcing  # 데이터베이스 URL
    username: root                       # 데이터베이스 사용자명
    password: namu0318                       # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스
  jpa:
    hibernate:
      ddl-auto: update                           # 자동 DDL 생성 (create, update, none 등)
    show-sql: true                               # SQL 쿼리 출력 여부
    properties:
      hibernate:
        format_sql: true                         # SQL 쿼리 포맷팅
# 로깅 설정
logging:
  level:
    root: info                                   # 기본 로깅 레벨
    org.springframework: debug                   # 특정 패키지 로깅 레벨 설정
# 기본 URL 설정 (옵션)
app:
  url:
    base: http://localhost:8080                  # 기본 URL 경로